apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: runme
  namespace: stateful
  description: Runme CLI
  annotations:
    github.com/project-slug: runmedev/runme
spec:
  type: service
  owner: user:runmedev/sourishkrout
  lifecycle: production
